#!/usr/bin/env bash
# Generate local secrets into .env (T046, FR-017): random MinIO/Postgres/Grafana credentials and a
# gateway API key. No secret is committed — .env is git-ignored; .env.example only documents.
# WSL/bootstrap counterpart to gen_secrets.ps1. Re-run with --force to rotate.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_PATH="$ROOT/.env"
FORCE="${1:-}"

if [[ -f "$ENV_PATH" && "$FORCE" != "--force" ]]; then
  echo ".env already exists at $ENV_PATH — not overwriting. Re-run with --force to rotate." >&2
  exit 0
fi

gen() { head -c "${1:-24}" /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32; }

MINIO_USER="mlops-$(gen 6)"
MINIO_PASS="$(gen 24)"
PG_PASS="$(gen 24)"
GRAF_PASS="$(gen 18)"
API_KEY="mll_$(gen 24)"

cat > "$ENV_PATH" <<EOF
# MLOps-Lite — LOCAL SECRETS (generated by scripts/gen_secrets.sh). DO NOT COMMIT.
# Non-secret settings keep their defaults from docker-compose.yml; override here if needed.

# Postgres (MLflow backend) — password is a generated secret.
POSTGRES_USER=mlops
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=mlflow
POSTGRES_PORT=55432

# MinIO (S3-compatible artifact + dataset storage) — generated credentials (no minioadmin).
MINIO_ROOT_USER=$MINIO_USER
MINIO_ROOT_PASSWORD=$MINIO_PASS
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001

# MLflow tracking + registry
MLFLOW_PORT=5500

# Gateway (FastAPI) + API-key auth (US1). Comma-separated to allow a small key set.
GATEWAY_PORT=8080
GATEWAY_API_KEYS=$API_KEY

# Observability — Grafana admin password is a generated secret.
PROMETHEUS_PORT=9090
GRAFANA_PORT=3001
GRAFANA_USER=admin
GRAFANA_PASSWORD=$GRAF_PASS
EOF

echo "Wrote $ENV_PATH with generated secrets."
echo
echo "Gateway API key (send as the 'X-API-Key' header):"
echo "  $API_KEY"
echo
echo "For tests/clients, export it in this shell:"
echo "  export GATEWAY_API_KEY='$API_KEY'"
