#!/usr/bin/env bash
# Generate local secrets into .env (T046, FR-017): random Postgres/Grafana credentials, the Garage
# node secrets, and a gateway API key. No secret is committed — .env is git-ignored; .env.example only documents.
# WSL/bootstrap counterpart to gen_secrets.ps1. Re-run with --force to rotate.
#
# 020 (T401) modes for the Garage store, whose credential flow is REVERSED vs the retired
# store (contracts/store-migration.md §bootstrap — Garage MINTS the S3 key pair and the operator
# records it; the old store took a pair generated here and fed INTO it):
#   --ensure-garage-secrets  append GARAGE_RPC_SECRET / GARAGE_ADMIN_TOKEN to an existing .env
#                            if missing (needed BEFORE garage first boots; idempotent)
#   --record-garage          run the idempotent garage-init one-shot and record the emitted
#                            GARAGE_ACCESS_KEY_ID / GARAGE_SECRET_ACCESS_KEY into .env
#                            (an already-recorded pair is kept and re-validated, never re-minted)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_PATH="$ROOT/.env"
MODE="${1:-}"

gen() { head -c "${1:-24}" /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32; }
gen_hex32() { head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }  # garage rpc_secret: 32-byte hex

# Always exits 0 (empty output on no match) — callers assign under set -e/pipefail.
env_get() { { grep -E "^${1}=" "$ENV_PATH" 2>/dev/null || true; } | head -1 | cut -d= -f2-; }

ensure_garage_secrets() {
  [[ -f "$ENV_PATH" ]] || { echo "no .env at $ENV_PATH — run scripts/gen_secrets.sh first." >&2; exit 1; }
  local added=0
  if [[ -z "$(env_get GARAGE_RPC_SECRET)" ]]; then
    printf '\n# Garage (020 US1) — node RPC secret + admin-API token (generated; DO NOT COMMIT).\nGARAGE_RPC_SECRET=%s\n' "$(gen_hex32)" >> "$ENV_PATH"
    added=1
  fi
  if [[ -z "$(env_get GARAGE_ADMIN_TOKEN)" ]]; then
    printf 'GARAGE_ADMIN_TOKEN=%s\n' "$(gen 24)" >> "$ENV_PATH"
    added=1
  fi
  [[ "$added" == 1 ]] && echo "Garage secrets ensured in $ENV_PATH." || echo "Garage secrets already present — unchanged."
}

record_garage() {
  [[ -f "$ENV_PATH" ]] || { echo "no .env at $ENV_PATH — run scripts/gen_secrets.sh first." >&2; exit 1; }
  echo "Running the garage-init one-shot (idempotent) to obtain the store-minted key pair..."
  local out key secret
  out="$(cd "$ROOT" && docker compose run --rm garage-init 2>&1)" || {
    echo "$out" | tail -5 >&2
    echo "garage-init failed — is the garage service up? (docker compose up -d garage)" >&2
    exit 1
  }
  key="$(printf '%s\n' "$out" | { grep -E '^GARAGE_ACCESS_KEY_ID=' || true; } | tail -1 | cut -d= -f2-)"
  secret="$(printf '%s\n' "$out" | { grep -E '^GARAGE_SECRET_ACCESS_KEY=' || true; } | tail -1 | cut -d= -f2-)"
  [[ -n "$key" && -n "$secret" ]] || { echo "garage-init emitted no key pair — output was:" >&2; printf '%s\n' "$out" | tail -10 >&2; exit 1; }
  local existing_key existing_secret
  existing_key="$(env_get GARAGE_ACCESS_KEY_ID)"
  existing_secret="$(env_get GARAGE_SECRET_ACCESS_KEY)"
  if [[ -n "$existing_key" && -z "$existing_secret" ]] || [[ -z "$existing_key" && -n "$existing_secret" ]]; then
    # Half a pair (hand-edit or an interrupted append): appending now would leave a duplicate
    # line for the var that already exists. Fail loud; the operator reconciles .env first.
    echo "ERROR: .env holds a PARTIAL Garage pair (one of GARAGE_ACCESS_KEY_ID /" >&2
    echo "GARAGE_SECRET_ACCESS_KEY without the other). Remove the stale line, then re-run." >&2
    exit 1
  fi
  if [[ -n "$existing_key" && -n "$existing_secret" ]]; then
    if [[ "$existing_key" == "$key" ]]; then
      echo "Garage key pair already recorded ($key) and matches the store — unchanged."
    else
      echo "WARNING: .env has GARAGE_ACCESS_KEY_ID=$existing_key but the store's key is $key." >&2
      echo "Keeping the recorded pair (never silently rotated). Reconcile manually if intended." >&2
    fi
    return 0
  fi
  {
    printf '\n# Garage S3 key pair — MINTED BY the store at bootstrap and recorded here\n'
    printf '# (scripts/gen_secrets --record-garage). DO NOT hand-edit or re-mint.\n'
    printf 'GARAGE_ACCESS_KEY_ID=%s\nGARAGE_SECRET_ACCESS_KEY=%s\n' "$key" "$secret"
  } >> "$ENV_PATH"
  echo "Recorded Garage key pair ($key) into $ENV_PATH."
}

case "$MODE" in
  --ensure-garage-secrets) ensure_garage_secrets; exit 0 ;;
  --record-garage)         record_garage;         exit 0 ;;
esac

if [[ -f "$ENV_PATH" && "$MODE" != "--force" ]]; then
  echo ".env already exists at $ENV_PATH — not overwriting. Re-run with --force to rotate." >&2
  exit 0
fi

PG_PASS="$(gen 24)"
GRAF_PASS="$(gen 18)"
API_KEY="mll_$(gen 24)"
GARAGE_RPC="$(gen_hex32)"
GARAGE_TOKEN="$(gen 24)"

cat > "$ENV_PATH" <<EOF
# MLOps-Lite — LOCAL SECRETS (generated by scripts/gen_secrets.sh). DO NOT COMMIT.
# Non-secret settings keep their defaults from docker-compose.yml; override here if needed.

# Postgres (MLflow backend) — password is a generated secret.
POSTGRES_USER=mlops
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=mlflow
POSTGRES_PORT=55432

# Garage (S3 artifact + dataset storage) — RPC secret + admin token are generated here; the
# S3 key pair is store-minted AFTER bootstrap: run scripts/gen_secrets --record-garage once
# `docker compose up -d garage garage-init` has run.
GARAGE_S3_PORT=3900
GARAGE_RPC_SECRET=$GARAGE_RPC
GARAGE_ADMIN_TOKEN=$GARAGE_TOKEN

# MLflow tracking + registry
MLFLOW_PORT=5500

# Gateway (FastAPI) + API-key auth (US1). Comma-separated to allow a small key set.
GATEWAY_PORT=8080
GATEWAY_API_KEYS=$API_KEY

# Observability — Grafana admin password is a generated secret.
PROMETHEUS_PORT=9090
GRAFANA_PORT=3001
GRAFANA_USER=admin
GRAFANA_PASSWORD=$GRAF_PASS
EOF

echo "Wrote $ENV_PATH with generated secrets."
echo
echo "Gateway API key (send as the 'X-API-Key' header):"
echo "  $API_KEY"
echo
echo "For tests/clients, export it in this shell:"
echo "  export GATEWAY_API_KEY='$API_KEY'"
