<#
.SYNOPSIS
  Generate local secrets into .env (T046, FR-017): random MinIO/Postgres/Grafana credentials and
  a gateway API key. No secret is ever committed — .env is git-ignored; .env.example only documents.

.DESCRIPTION
  Writes a fresh .env (non-secret defaults + generated secrets). Refuses to overwrite an existing
  .env unless -Force, so re-runs don't silently rotate live credentials. Prints the API key once.

.EXAMPLE
  ./scripts/gen_secrets.ps1
  ./scripts/gen_secrets.ps1 -Force
#>
param([switch]$Force)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $root ".env"

if ((Test-Path $envPath) -and -not $Force) {
    Write-Host ".env already exists at $envPath — not overwriting. Re-run with -Force to rotate." -ForegroundColor Yellow
    exit 0
}

function New-Secret([int]$bytes = 24) {
    $b = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($b)
    # Base64 then strip non-alphanumerics -> shell/URL-safe credential.
    return ([Convert]::ToBase64String($b) -replace '[^A-Za-z0-9]', '')
}

$minioUser = "mlops-" + (New-Secret 6)
$minioPass = New-Secret 24
$pgPass    = New-Secret 24
$grafPass  = New-Secret 18
$apiKey    = "mll_" + (New-Secret 24)

$content = @"
# MLOps-Lite — LOCAL SECRETS (generated by scripts/gen_secrets.ps1). DO NOT COMMIT.
# Non-secret settings keep their defaults from docker-compose.yml; override here if needed.

# Postgres (MLflow backend) — password is a generated secret.
POSTGRES_USER=mlops
POSTGRES_PASSWORD=$pgPass
POSTGRES_DB=mlflow
POSTGRES_PORT=55432

# MinIO (S3-compatible artifact + dataset storage) — generated credentials (no minioadmin).
MINIO_ROOT_USER=$minioUser
MINIO_ROOT_PASSWORD=$minioPass
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001

# MLflow tracking + registry
MLFLOW_PORT=5500

# Gateway (FastAPI) + API-key auth (US1). Comma-separated to allow a small key set.
GATEWAY_PORT=8080
GATEWAY_API_KEYS=$apiKey

# Observability — Grafana admin password is a generated secret.
PROMETHEUS_PORT=9090
GRAFANA_PORT=3001
GRAFANA_USER=admin
GRAFANA_PASSWORD=$grafPass
"@

Set-Content -Path $envPath -Value $content -Encoding UTF8 -NoNewline
Write-Host "Wrote $envPath with generated secrets." -ForegroundColor Green
Write-Host ""
Write-Host "Gateway API key (send as the 'X-API-Key' header):" -ForegroundColor Cyan
Write-Host "  $apiKey"
Write-Host ""
Write-Host "For tests/clients, expose it in this shell:" -ForegroundColor Cyan
Write-Host "  `$env:GATEWAY_API_KEY = '$apiKey'"
